import { runTests } from "https://deno.land/std@v0.32.0/testing/mod.ts";

import "./curry.test.ts";
import "./head.test.ts";
import "./tail.test.ts";
import "./map.test.ts";
import "./filter.test.ts";
import "./reduce.test.ts";
import "./reverse.test.ts";
import "./compose.test.ts";
import "./pipe.test.ts";
import "./identity.test.ts";
import "./omit.test.ts";
import "./values.test.ts";
import "./keys.test.ts";
import "./split.test.ts";
import "./sort.test.ts";
import "./concat.test.ts";
import "./equals.test.ts";
import "./find.test.ts";
import "./flatten.test.ts";
import "./has.test.ts";
import "./nth.test.ts";
import "./prop.test.ts";
import "./group_by.test.ts";
import "./includes.test.ts";
import "./last.test.ts";
import "./pluck.test.ts";
import "./slice.test.ts";
import "./pick.test.ts";

runTests();
